
{'date': 'Mon Sep 21 2020 20:14:02.801 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  #circus(<ponha aqui o número do desafio e descomente a linha>, <parâmetro indicado>)
                                                                                      ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 21 2020 20:14:11.881 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  #circus(<ponha aqui o número do desafio e descomente a linha>, <parâmetro indicado>)
                                                                                      ^
IndentationError: expected an indented block
'''},
{'date': 'Mon Sep 21 2020 20:14:19.344 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  if __name__ == "__main__":#circus(<ponha aqui o número do desafio e descomente a linha>, <parâmetro indicado>)
                                                                                                                ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Sep 22 2020 12:35:49.481 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    circus(3, MASMORRA)
NameError: name 'MASMORRA' is not defined
'''},
{'date': 'Tue Sep 22 2020 14:01:16.622 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 46
    desafio2()
  module <module> line 35
    circus(2, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: D
'''},
{'date': 'Tue Sep 22 2020 14:01:28.924 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 46
    desafio2()
  module <module> line 35
    circus(2, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: D
'''},
{'date': 'Wed Sep 23 2020 09:15:57.810 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    desafio4()
  module <module> line 51
    circus(4, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 09:16:21.516 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    desafio4()
  module <module> line 51
    circus(4, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 09:16:27.335 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    desafio4()
  module <module> line 51
    circus(4, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 09:17:26.401 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 50
    desafio4()
  module <module> line 47
    circus(4, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:01:39.435 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 131
    self.desafio0(c)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: a
'''},
{'date': 'Wed Sep 23 2020 11:01:45.46 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 131
    self.desafio0(c)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: a
'''},
{'date': 'Wed Sep 23 2020 11:01:50.924 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 131
    self.desafio0(c)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: a
'''},
{'date': 'Wed Sep 23 2020 11:02:00.830 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 131
    self.desafio0(c)
  module circus.circus line 123
    c = [Piso(self.cena, 10*LADO+i*LADO, j*LADO, ai ) for j, linha in enumerate(solucao) for i, ai in enumerate(linha)]
  module circus.circus line 33
    az = azz[ai[1]]
KeyError: a
'''},
{'date': 'Wed Sep 23 2020 11:02:24.718 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:02:38.209 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:03:06.292 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:03:07.664 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:03:41.803 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:03:47.694 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:03:49.965 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:04:13.910 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:05:26.199 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 58
    desafio5()
  module <module> line 55
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Wed Sep 23 2020 11:06:52.499 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Fri Sep 25 2020 21:00:46.79 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Fri Sep 25 2020 21:01:37.836 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Fri Sep 25 2020 21:01:50.176 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Fri Sep 25 2020 21:02:30.570 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Fri Sep 25 2020 21:06:51.481 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Mon Sep 28 2020 13:51:24.846 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},
{'date': 'Mon Sep 28 2020 13:51:39.637 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    desafio5()
  module <module> line 53
    circus(5, MASMORRA)
  module circus.circus line 179
    Aldeia(Jogo()).circus(desafio, solucao, desafio)
  module circus.circus line 158
    self.desafios[desafio](solucao)
  module circus.circus line 135
    self.desafio2(solucao)
  module circus.circus line 130
    c = [[solucao[ai] for ai in linha] for linha in Aldeia.KEYS]
AttributeError: 'Aldeia' object has no attribute 'KEYS'
'''},